### ISSUE TITLE
Safe Apps deep linking

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#414]
## Overview
Related to this problem statement https://github.com/gnosis/safe-pm/issues/60
Currently is not possible to share a link to a Safe App directly in the Safe web. Whenever you try to share a Safe App via link with another person it will also include the current Safe used to open the dApp, instead of allowing a link that would open with a Safe this other person own

## Goals

- [x] https://github.com/gnosis/safe-react-apps/issues/411
- [x] https://github.com/gnosis/safe-react-apps/issues/412
- [x] https://github.com/gnosis/safe-react-apps/issues/413
- [ ] https://github.com/gnosis/safe-react-apps/issues/416
- [x] https://github.com/gnosis/safe-react-apps/issues/426

## Screens
[Figma designs](https://www.figma.com/file/v56CKWh6Yp60cSsZ71URB0/dApp-sharing-functionality?node-id=81%3A1585)
