### ISSUE TITLE
[EPIC][TX-Builder] Enable proxy detection

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#456]
## Overview
After discussing that proxy contracts are not straight forward to use in the TX-Builder https://github.com/safe-global/safe-pm/issues/63 we decided to enable automatic check to detect when a contract is a proxy and offer the user the possibility of loading the implementation ABI 

## Goals
- Detect most common and standard proxy patterns
- Offer to change implementation ABI, do not change without noticing the user
- Allow user to review implementation address and check in block explorer
- Positive answer just replace the ABI, keep in other case.

## Requirements

- [ ] Proxy contract detect. There can be different patterns
- [ ] Detect if an ABI can be resolved in that implementation address
- [ ] Suggest the change to the user
- [ ] Swap when confirming

## Screens
<img width="739" alt="imagen" src="https://user-images.githubusercontent.com/25051234/173390646-6742e931-65b3-4691-b97e-335992bebab3.png">

 - Figma: https://www.figma.com/file/G7snLqBXWNPANcOj5MhiR7/Transaction-Builder?node-id=1704%3A9019

**Comment by mikhailxyz** [comment]
RFC for the problem can be found here: https://docs.google.com/document/d/1WGd6ToCTTTgfnQmtjsYX7DCnrszUXJ38c-8oRsAvaL0/edit
