### ISSUE TITLE
[EPIC] Safe Apps Workshop

### ISSUE THREAD

**Issue by DaniSomoza** [safe-global/safe-react-apps#485]
## Goals
- [ ] Create a Workshop project
  - [x]  Create a [repository](https://github.com/5afe/safe-apps-workshop)
  - [ ]  Create a Counter DApp using Onboard
  - [ ]  Create a Counter Safe App Integration using Onboard
  - [ ]  Create a Counter Safe App Integration using our SDK
- [ ] Create & Review Docs
- [ ] Create Slides ([Draft here](https://docs.google.com/presentation/d/1l6DqRlIEpCri3XUn9gM4kOdjgLWBR85JMBksYgAVDLA/))
