### ISSUE TITLE
[EPIC] Sign in Safe App

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#493]
## Overview
We will create a new Safe App to handle Sign in with Ethereum (Siwe) delgate registry. The delegate registry is already deployed. We just need an interface to handle interactions with this registry.

## Roadmap Epic:
https://www.notion.so/gnosis-safe/Sign-in-with-Safe-Management-App-a827162ef3324dbfa0d7fafc59bbf1da

## Requirements
- [ ] Add delegate for login.xyz (Siwe) to the delegate registry smart contract
- [ ] Check current active delegates allowed to use SiWe
- [ ] Remove a SiWe delegate from the smart contract
- [ ] Use static string `SiWe` as `id`

The delegate registry is a smart contract that is deterministically deployed to this address `0x469788fE6E9E9681C6ebF3bF78e7Fd26Fc015446`

We can assume this address is available on `mainnet` and `goerli`. In the future we may enable for other chains, but not for the first version.
Code is available here https://github.com/gnosis/delegate-registry/tree/main

An example Dapp for testing can be found in the following repository
https://github.com/spruceid/siwe/

## Screens
![imagen](https://user-images.githubusercontent.com/25051234/200296151-7d7ffc04-f97b-4257-a404-015f3e92e7c3.png)

## Links
 - Delegate registry repository https://github.com/gnosis/delegate-registry/tree/main

**Comment by johannesmoormann** [comment]
Comments on the prototype: 

**Discoverability & Education**
- We should include a list of projects that currently use this delegation contract. Especially mentioning SiWe here and a one-liner over the use case
- app description should also state SiWe and Snapshot since this is the main use case for now
- discuss with SiWe how on the other end the user will discover this app @johannesmoormann 

**Spaces**

- at snapshot, the space for delegation gets filled automatically, how would the user know what to choose here as we cannot provide a dropdown yet with choices. 
- in the current implementation we could add a dropdown saying SiWe but there is no on-chain address that we could actually use for that 
- I would therefore suggest adding an info icon with hover message saying "Spaces are currently only utilized by Snapshot" to the spaces toggle and Space table description

Text changes:
- "lorem ipsum..." -> "The Delegate Registry Contract allows owners of a Safe to delegate certain off-chain rights to another wallet e.g. gasless signing into a social application or gasless voting on behalf of a Safe." 
- add security info box: "Safe has no influence on what off-chain actions other projects allow set delegates in the Delegation Registry Contract. However, delegates do not have any control over on-chain assets in the Safe."
- add info icon to space toggle and text tbd

**Comment by dasanra** [comment]
External feedback

> Giving some review now of the app: 
>- Agreed with the comments on spaces - because the scopes at this point aren't limited, it might make sense to redact >giving an offer to limit it to a specific space until more work is done on that. 
>- It might make sense to really bullet out the immediate use-cases to make them extra clear with what's going on 
>- Is there a way to bulk add delegates or would it just be one-by-one 
>- Would there be a way in the future for the creation flow of Safes to have an advanced mode that bundles this into the >transaction and set delegates from the onset? 
>- Are there any additional statuses other than confirmed? Would it make sense to just assume that all delegates in the >delegations table are valid?

**Comment by DaniSomoza** [comment]
WIP Doc: https://www.notion.so/gnosis-safe/Registry-Manager-Safe-App-bf3324ae89cb477fa2ce13b79d39a191

**Comment by mikhailxyz** [comment]
The screenshot in the issue mentions links to the help center articles but no help center article links. Where can I find them?
