### ISSUE TITLE
[Epic] Safe Apps list curation is centralized

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#555]
## Overview
We will research how to decentralize the listing process for Safe Apps, looking for the best approach in terms of incentives and make the ecosystem grow

## Requirements

- [ ] Problem discovery
- [ ] Workshop to review the current state and guide product discovery session
- [ ] Workshop to set the objectives and constraint the solution
- [ ] Solution design. Create a document drafting the technical solution
- [ ] Workshop to review the solution and get feedback from the solution
- [ ] Publish the solution to be reviewed by the community

## Links

https://www.notion.so/gnosis-safe/Safe-Apps-Curation-Process-is-Centralized-bb938340142c44bea45bac7c9e0423c2
